---
- name: packages.yml | installing default packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ packages }}"

- name: packages.yml | installing dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb

