---
- name: x1.yml | install requirements
	apt:
		name: "{{ item }}"
		update_cache: yes
	with_items:
		- virtualenv
		- build-essential
		- python3-dev
		- libdbus-glib-1-dev
		- libgirepository1.0-dev
		- libcairo2-dev

- name: x1.yml | clone lenovo fix repo for x1 carbon
	git:
		repo: https://github.com/erpalma/lenovo-throttling-fix.git
		dest: /opt

- name: x1.yml | install lenovo fix
  shell: cd /opt/lenovo-throttling-fix; ./install

- name: x1.yml | disable termald
  systemd:
    state: stopped
    name: termald
    masked: yes
    enabled: no

- name: x1.yml | systemctl restart lenovo-throttling-fix
  systemd:
    state: restarted
    name: lenovo_fix.service
    enabled: yes

- name: x1.yml | disabling memory card reader
  shell: echo "2-3" | tee /sys/bus/usb/drivers/usb/unbind

- name: x1.yml | installing battery saving pkgs
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - tlp
    - tlp-rdw
    - acpi-call-dkms
    - tp-smapi-dkms
    - acpi-call-dkms
