---
- name: zsh.yml | installing oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: zsh.yml | installing zsh-autosuggestions
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  failed_when: false

- name: zsh.yml | installing zsh-syntax-highlighting 
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting; 

- name: zsh.yml | installing fzf-zsh
  git:
    dest: ~/.fzf
    repo: https://github.com/junegunn/fzf.git
    force: yes
    update: yes

- name: zsh.yml | installing fzf-zsh 2
  shell: ~/.fzf/install

- name: zsh.yml | installing base16-shell
  git:
    dest: ~/.config/base16-shell
    repo: https://github.com/chriskempson/base16-shell.git
    update: yes
    force: yes
    
- name: zsh.yml | copy custom base16 theme
  copy:
    src: base16-luca.sh
    dest: ~/.config/base16-shell/scripts

- name: zsh.yml | copy luca.zsh-theme
  copy:
    src: luca.zsh-theme
    dest: ~/.oh-my-zsh/themes

- name: zsh.yml | copy .zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc

- name: zsh.yml | copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
